In [1]:
import numpy as np

# Create a sample numpy array A
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Define the rows i and j that you want to interchange
i, j = 0, 2

# Interchange rows i and j
A[[i, j]] = A[[j, i]]

# Print the modified array A
print(A)


[[7 8 9]
 [4 5 6]
 [1 2 3]]
