In [1]:
import numpy as np

x = np.random.rand(5) #generates a 1D NumPy array x of length 5 filled with random numbers between 0 and 1 using the np.random.rand function.

D = np.subtract.outer(x, x)  #np.subtract.outer(x, x) will be a 2D array where each element at position [i][j] represents the result of subtracting x[i] from x[j].
print(D)

[[ 0.          0.36482965  0.41909208  0.37261912  0.00981342]
 [-0.36482965  0.          0.05426243  0.00778947 -0.35501623]
 [-0.41909208 -0.05426243  0.         -0.04647296 -0.40927866]
 [-0.37261912 -0.00778947  0.04647296  0.         -0.3628057 ]
 [-0.00981342  0.35501623  0.40927866  0.3628057   0.        ]]


In [2]:
#extanded version
A = np.zeros((5,5))
for i in range(5):
  for j in range (5):
    A[i][j]=x[i]-x[j]

print(A)

[[ 0.          0.36482965  0.41909208  0.37261912  0.00981342]
 [-0.36482965  0.          0.05426243  0.00778947 -0.35501623]
 [-0.41909208 -0.05426243  0.         -0.04647296 -0.40927866]
 [-0.37261912 -0.00778947  0.04647296  0.         -0.3628057 ]
 [-0.00981342  0.35501623  0.40927866  0.3628057   0.        ]]
